### ISSUE TITLE
GUI for the Open Source Project

### ISSUE THREAD

**Issue by PierrunoYT** [gpt-engineer-org/gpt-engineer#1008]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/
 - Consider adding the label "good first issue" for interesting, but easy features.

## Feature description
I would love the see a GUI which you can run on localhost because I don't like the terminal thing.

## Motivation/Application
I think it's usefull to have more oversight over the whole process and it's easiert to understand what happens and also it's more attractive.

**Comment by viborc** [comment]
Closing in favor of #505 and the conversation there.
