### ISSUE TITLE
API Key Issue

### ISSUE THREAD

**Issue by PierrunoYT** [gpt-engineer-org/gpt-engineer#1012]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/

## Expected Behavior

Please describe the behavior you are expecting.
I want to save the API Key forever

## Current Behavior

What is the current behavior?
Every time I restart cmd I need to reenter the api key.

**Comment by captivus** [comment]
This is expected behavior. You'll need to configure persistent environment variables if you don't want to have to do this. Here is a reference: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/set_1
