### ISSUE TITLE
Feature request: Windows script for running code generated by GPT-Engineer

### ISSUE THREAD

**Issue by similato87** [gpt-engineer-org/gpt-engineer#1019]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/
 - Consider adding the label "good first issue" for interesting, but easy features.

## Feature description
The gpt-engineer project currently only has a script for running on Linux systems. To enhance accessibility and convenience, it would be beneficial to provide a Windows-compatible script (using either batch (.bat) or PowerShell (.ps1) format).

Ideally, when using GPT-Engineer to generate new projects, this enhanced setup should include one of the following options:
- Auto-detection: The script can automatically detect the operating system (Windows or Linux) and execute the appropriate setup instructions.
- Separate scripts: Provide clearly named scripts for both Windows and Linux, allowing users to select the one they need.

**What we have now is a script for linux shell**
![image](https://github.com/gpt-engineer-org/gpt-engineer/assets/71301573/d4611367-d6bd-412b-bb66-b7535340f16d)

## Motivation/Application
- Cross-Platform Usability: Windows users would be able to easily utilize GPT-Engineer to generate and manage projects.
- Project Setup Streamlining: New projects generated by GPT-Engineer could be directly initiated with the right setup across both Windows and Linux environments without manual adjustments.

**Comment by viborc** [comment]
As a Windows/WSL user, I support this!

**Comment by ATheorell** [comment]
I have a slightly modified idea!

Currently, in the "entrypoint" preprompt, we say this:

... that includes all the necessary unix terminal ...

Instead, we could make this part of the preprompt depend on 

```
from platform import platform
f"\nOS: {platform()}\n"
```

so that it adapts the entrypoint to the platform. Similarly, we should adapt the name of the runnable file. What do you think @similato87 ?

**Comment by similato87** [comment]
Thanks, @ATheorell, for the great suggestion! I've incorporated your idea into the setup process, making the preprompt and file naming OS-specific. The changes are now in a PR. Appreciate your guidance!
