### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by oldmanjk** [gpt-engineer-org/gpt-engineer#1032]
## Expected Behavior

Work

## Current Behavior

Doesn't work.
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4864: character maps to <undefined>`

## Failure Information

Windows 11

### Steps to Reproduce

`gpte` [presumably, anything containing Unicode] `-i`

### Failure Logs

```
Traceback (most recent call last):

  File "C:\Users\J\AppData\Local\pypoetry\Cache\virtualenvs\gpt-engineer-woB2nRrJ-py3.12\Scripts\\gpte", line 6, in <module>
    sys.exit(app())
             ^^^^^

  File "C:\Users\J\gpt-engineer\gpt_engineer\applications\cli\main.py", line 273, in main
    files_dict = fileselector.ask_for_files()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\J\gpt-engineer\gpt_engineer\applications\cli\file_selector.py", line 108, in ask_for_files
    content_dict[str(file_path)] = content.read()
                                   ^^^^^^^^^^^^^^

  File "C:\Users\J\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4864: character maps to <undefined>
```

### Extra

Was fixed in https://github.com/gpt-engineer-org/gpt-engineer/pull/801 , but looks like it got lost in a move. gpt_engineer/applications/cli/file_selector.py around line 107 is what needs fixing again

**Comment by TheoMcCabe** [comment]
Thanks - let me put up a PR for this 

> Can confirm changing line 107 from `with open(Path(self.project_path) / file_path, "r") as content:` to `with open(Path(self.project_path) / file_path, "r", encoding="utf-8") as content:` works

**Comment by AntonOsika** [comment]
I actually think I addresd this in my other PR theo (since I had the same
issue) can we try merging that first?

Anton Osika
