### ISSUE TITLE
Make it possible to use "copy paste" to external LLM for Gemini 1.5 experimentation

### ISSUE THREAD

**Issue by AntonOsika** [gpt-engineer-org/gpt-engineer#1036]
Just got access to Gemini 1.5.

It supposedly performs super well with long prompts + million token context window.

To run it I right now have to:

- pipe codebase and system prompt to clipboard
- use Gemini web UI
- copy paste results back to e.g. gpt-engineer to apply to codebase

Would love help with this since my calendar is packed and then I'd be happy to run any experiment on an open source repo for the community. 

I think solution is something like this:

```python
import pyperclip

class ClipboardAI:
  def next(self, messages):
    msgs = messages_to_str(messages)
    pyperclip.copy(msgs)
    return str_to_messages(multiline_input())
    
    
def multiline_input():
  print("Enter/Paste your content. Ctrl-D or Ctrl-Z ( windows ) to save it.")
  content = []
  while True:
    try:
        line = input()
    except EOFError:
        break
    content.append(line)
  return content
```

As well as skipping the selection step but just feeding all the files in a given directory.

Should be straightforward to add a new agent for this.

**Comment by TheoMcCabe** [comment]
Nice i would use this too - happy to implement it - @viborc  its been moved to in progress without an owner - is someone picking it up?

**Comment by viborc** [comment]
I'm happy to assign you @TheoMcCabe right now!

**Comment by AntonOsika** [comment]
Thanks Both! <3

Yes I think my PR should be good.
Would love a quick review Theo (and if you know why we're getting the
"missing openai key" failure in tests")

Anton Osika

**Comment by TheoMcCabe** [comment]
All looks good to me- approved.
