### ISSUE TITLE
Set up codecov.io reporting

### ISSUE THREAD

**Issue by ErikBjare** [gpt-engineer-org/gpt-engineer#1038]
I was curious about what the test coverage looked like, and found: https://github.com/gpt-engineer-org/gpt-engineer/issues/780

While it's great that we've thought a bit about of it already, I'd like us to set up [codecov.io](https://codecov.io) reporting to:
 - Track how it changes over time.
 - Get notified about whether lines changed by PRs are covered by tests or not.
   - Makes code coverage more visible to contributors and maintainers, thus helping inform the adequacy of testing.
 - Easily explore which parts of the codebase are well tested, and which might need work. (the pytest/coverage CLI/HTML reporting is okay for this, but codecov.io is better imo)

codecov.io is free for open source.

I volunteer to do this, but I need maintainer access.

**Comment by ATheorell** [comment]
Great idea and great that you volunteer @ErikBjare . You are now maintainer. I really thought you were already!

**Comment by ErikBjare** [comment]
@ATheorell Apparently I need org-wide access to do the final confirmation.

**Comment by captivus** [comment]
I have approved installation.

**Comment by captivus** [comment]
Check your Discord DMs @ErikBjare for API key from CodeCov.
