### ISSUE TITLE
WSL2 gpte File List bad Behavior

### ISSUE THREAD

**Issue by oldmanjk** [gpt-engineer-org/gpt-engineer#1046]
## Expected Behavior

WSL2 `gpte` uses existing `.gitignore`, then gives opportunity to select and deselect files, save, and close.
Else use existing `file_selection.toml`.
Else use existing `.gitignore`.
Else don't overwrite existing files!
Else don't overwrite existing read-only files!

## Current Behavior

WSL2 `gpte` generates its own `.gitignore`, overwriting existing `.gitignore`, even when `.gitignore` is read-only, then generates its own `file_selection.toml`, based on its own `.gitignore`, overwriting existing `file_selection.toml`.

## Failure Information

Windows 11 WSL2 Ubuntu

### Steps to Reproduce

`$ gpte project -i`

### Failure Logs

`File list detected at /mnt/c/Users/J/gpt-engineer/projects/`[project]```
/.gpteng/file_selection.toml. Edit or delete it if you want to select new files.
Please select and deselect (add # in front) files, save it, and close it to continue...
write: /mnt/c/Users/J/gpt-engineer/projects/
```[project]`/.gpteng/file_selection.toml is not logged in`

**Comment by ATheorell** [comment]
Ok, sounds quite serious with the overwrite. Can you look into this @Styren ?

**Comment by ATheorell** [comment]
Thanks for pushing this. Yes, this indeed sounds very problematic

**Comment by Styren** [comment]
Strange, there's no code path that _should_ generate a .gitignore file, @oldmanjk what is the content of the `.gitignore` that overwrites the existing file? And what is the content of the generated `file_selection.toml`?

**Comment by captivus** [comment]
I'm unable to reproduce this @oldmanjk .  Can you please provide more details on how you are able to reproduce?  Does this happen consistently, or was this a once-off issue?

**Comment by captivus** [comment]
Are you hosting a local model?  Otherwise, can you tell us more about this seemingly local chat server you're interacting with?

```
INFO:httpx:HTTP Request: POST http://192.168.1.79:5000/v1/chat/completions "HTTP/1.1 200 OK"
Traceback (most recent call last):
```

**Comment by captivus** [comment]
That is a relevant detail as the issue isn't reproducible with the details you've provided and the files that are created are generated by the model directly. We will keep this issue open to see if others report a similar problem but, being unable to reproduce the issue, and without a direct cause evident in the codebase as previously observed by @Styren, we have no immediate next actions.

**Comment by captivus** [comment]
Calm down.  We can't reproduce your issue.  We're keeping this open to collect additional, and hopefully more detailed, information on this.  If you can provide more detailed information to help us reproduce this issue, we're keen for it.  We're also keen for others to provide details on this issue, as they experience the same.
