### ISSUE TITLE
 Implement Vector Store for Similarity-Based Code Generation (RAG on Codebase)

### ISSUE THREAD

**Issue by moamen270** [gpt-engineer-org/gpt-engineer#1048]
## Feature description
I've been exploring your repository and I'm fascinated by the capabilities of the agent as a software engineer, particularly in executing commands and calling functions. However, I believe there's a significant opportunity to enhance its capabilities by integrating a vector store that contains embedded codebases. This would enable the agent to perform similarity searches on code snippets, allowing it to generate code similar to existing codebases.

## Motivation/Application
Why is this feature useful?
The agent will be able to produce code that closely resembles existing codebases, improving the quality and relevance of generated code. By leveraging similarity-based code generation, the agent can adapt to different coding styles and conventions present in the embedded codebases.

**Comment by viborc** [comment]
Hey, @moamen270, thanks for this feature request! We just discussed it during our meeting. At the moment, we should focus more on other open issues and our roadmap goals. Our current thinking is that with increased context sizes of (most) modern models, implementation of Vector Stores and RAG functionality might not be a very high priority.

We previously experimented with that (I think you can probably find those commits in this repo), and our experience was that it also brought some additional complexities and the need for additional dependencies.

**Comment by lexasub** [comment]
Hello, @viborc! On the one hand yes, on the other hand - I have on rtx 3060 + 32 gb ram does not fit all the context (code), which is very sad. i got the boilerplate, but further planned to edit myself and give gpt-engeener alternately. but with my resources this is not possible, any promotion on this issue?
