### ISSUE TITLE
Run against SWE-Bench

### ISSUE THREAD

**Issue by batwood001** [gpt-engineer-org/gpt-engineer#1062]
## Feature description
Devin, the "First AI software engineer" is using their SWE-Bench performance as primary evidence of their capability.

## Motivation/Application
Provide a benchmark to evaluate Devin's claims, and solidify gpt-engineer's reputation as a legitimate autonomous coding agent.

**Comment by ErikBjare** [comment]
I also had the urge to implement this after the Devin announcement 😄 

But there is already an issue for it: https://github.com/gpt-engineer-org/gpt-engineer/issues/913

Closing as duplicate, continuing the discussion in the above issue.
