### ISSUE TITLE
Disentangle tests by removing cachingAI

### ISSUE THREAD

**Issue by ATheorell** [gpt-engineer-org/gpt-engineer#1076]
Some time back I made the unfortunate decision of implementing a "CachingAI" class that allows us to run tests here on github without an openai api key. It turns out that, using CachingAI in unit tests, instead of simpler mocks makes the tests highly tangled -- changing one thing often leads  to a plethora failed tests and its hard to trace why they fail -- the opposite of the intention of unit tests. 

To remedy this, we should remove the CachingAI class completely and replace its usage in the tests with mocks, EXCEPT for the top level tests, which should be evaluated live with openai_key (yes we can use that on github).

The specific tests that should be _deep_ are the top level tests in test_main.py, specifically:

    def test_default_settings_generate_project(self, tmp_path, monkeypatch):

    def test_improve_existing_project(self, tmp_path, monkeypatch):

    def test_lite_mode_generate_project(self, tmp_path, monkeypatch):

    def test_clarify_mode_generate_project(self, tmp_path, monkeypatch):

    def test_self_heal_mode_generate_project(self, tmp_path, monkeypatch):

and in test_install.py:

    def test_installed_main_execution

**Comment by ErikBjare** [comment]
We should consider using pytest markers to annotate the tests that rely on inference (or simply use a conditional skip if there is no OPENAI_API_KEY in the env), so that they can be toggled.

**Comment by ATheorell** [comment]
> We should consider using pytest markers to annotate the tests that rely on inference (or simply use a conditional skip if there is no OPENAI_API_KEY in the env), so that they can be toggled.

Makes sense
