### ISSUE TITLE
No chance to input and answer the gpte three question on generate complex application

### ISSUE THREAD

**Issue by zhoumzh** [gpt-engineer-org/gpt-engineer#1091]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/

## Expected Behavior

Please describe the behavior you are expecting.
i want to generate a complex application
## Current Behavior
gpte konwn this and gpte said like this
What is the current behavior?
![image](https://github.com/gpt-engineer-org/gpt-engineer/assets/11206821/b0bd7050-71d1-4222-8efa-9588767a7ab3)
But he didn't give me a chance to input and answer his three questions

## Failure Information

Information about the failure, including environment details, such as LLM used.

### Failure Logs

If your project includes a debug_log_file.txt, kindly upload it from your_project/.gpteng/memory/ directory. This file encompasses all the necessary logs. Should the file prove extensive, consider utilizing GitHub's "add files" functionality.

**Comment by viborc** [comment]
Quick question here @zhoumzh - which version of gpt-engineer did you use when you noticed this?

**Comment by zhoumzh** [comment]
@viborc  just Current latest version. Can reproduce stably tks!

**Comment by viborc** [comment]
Can you try using 0.2.9 now and let me know if it's still happening, please?

**Comment by viborc** [comment]
I'm closing this issue. If you want to reopen it, feel free to do so.
