### ISSUE TITLE
How to use Anthropic models

### ISSUE THREAD

**Issue by lassebenni** [gpt-engineer-org/gpt-engineer#1097]
## Expected Behavior

I am running version `2.8`.

I want to use the `claude-3-opus-20240229` model but I am confused on how to run this, the documentation seems lacking.

I performed the following steps:

1. Added the `ANTHROPIC_API_KEY` environment variable with my API key.
2. Ran `gpt-engineer . claude-3-opus-20240229` (latest model).

Getting:
```
NotFoundError: Error code: 404 - {'error': {'message': 'The model `claude-3-opus-20240229`
does not exist or you do not have access to it.', 'type': 'invalid_request_error', 
'param': None, 'code': 'model_not_found'}}
```

I verified that the model is correct, since I can run the example code from anthropic's docs fine:
```
import anthropic

client = anthropic.Anthropic(
)
message = client.messages.create(
    model="claude-3-opus-20240229",
    max_tokens=1000,
    temperature=0,
    messages=[
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "Hi!\n"
                }
            ]
        }
    ]
)
print(message.content)
```

What's the issue here?

**Comment by ErikBjare** [comment]
You need to use the latest version from git, v0.2.8 doesn't have support for Anthropic.
