### ISSUE TITLE
Investigate/document how to use with OpenRouter

### ISSUE THREAD

**Issue by ErikBjare** [gpt-engineer-org/gpt-engineer#1099]
As I mentioned in https://github.com/gpt-engineer-org/gpt-engineer/pull/1082#pullrequestreview-1963599143, OpenRouter is an easy way to run lots of different LLMs through a OpenAI-compatible API (notably recommended by Aider).

We should consider investigating this as a user-friendly way to use open models without needing your own hardware, and document it accordingly.

@zigabrencic did some investigation on this. Opening this issue to track our investigation and potentially documenting to users how to use it.

One notable downside of it, and open models generally, is that it may lead to all kinds of bugs caused by less powerful models. We might want to mention this in docs so that users are aware, and don't open spurious bug reports.

**Comment by zigabrencic** [comment]
@vibor you can assign me to this one. Will start looking into it at towards the end of the week.

**Comment by viborc** [comment]
Done, thanks @zigabrencic!

**Comment by TheoMcCabe** [comment]
I wrote an article on this 

https://medium.com/@tedisaacs/from-openai-to-opensource-in-2-lines-of-code-b4b8d2cf2541

**Comment by TheoMcCabe** [comment]
Yeah i saw the same thing with mynt. The only things that could handle the logic required to contruct the requests properly were anthropic or open ai models. Even google gemini sucked!  

There are other benefits to using open router other than just getting access to more models... like being visible on the open router app rankings. 

I'd say the models not working very well shouldnt be a blocker on us completing this integration

**Comment by TheoMcCabe** [comment]
I think this can be closed now as you PR is merged  @zigabrencic ?
