### ISSUE TITLE
Ollama Multithreaded UI integration, issue with code testing below python 3.10

### ISSUE THREAD

**Issue by 6rz6** [gpt-engineer-org/gpt-engineer#1102]
Need to verify code test #3 doesn't cause breaks due to dependency on python  <3.8

**Comment by 6rz6** [comment]
[@eleijonmarck ](https://github.com/ErikBjare) - Merge confirmed

**Comment by ErikBjare** [comment]
Python versions lower than 3.10 are not supported.

I think the Ollama stuff you built in https://github.com/gpt-engineer-org/gpt-engineer/pull/1098 makes more sense as a seperate repo.

Closing.
