### ISSUE TITLE
Getting "Could not resolve authentication method" – without a stacktrace

### ISSUE THREAD

**Issue by AntonOsika** [gpt-engineer-org/gpt-engineer#1110]
We merged a global try catch, which I think is a bad idea.

I'm running with claude opus and when it fails I cannot see what the problem is due to the global try catch

Logs:

[debug_log_file.txt](https://github.com/gpt-engineer-org/gpt-engineer/files/14963928/debug_log_file.txt)

@similato87 have we used the logs so far? If not I think we should remove it or rework it.

**Comment by similato87** [comment]
Hi @AntonOsika , I apologize for any inconvenience this issue has caused. I understand your concerns about the global try-catch and appreciate you bringing this to my attention. Originally, we implemented this to capture exceptions related to user files more effectively, which has helped improve our logging for the new "diff" feature. We've received several valuable reports from this without needing excessive communication with our users.

However, I see how this can obscure the clarity of error reporting, especially in cases like yours with Claude Opus. I will work on a hotfix to address this by narrowing the scope of the try-catch and ensuring that stack traces are preserved for better error visibility.

**Comment by AntonOsika** [comment]
Thanks @similato87!

Do you have a propose to how to fix it?

**Comment by similato87** [comment]
Hello @AntonOsika,

I have implemented a function to print the stack trace within the try-catch block, allowing us to view the trace both on the console and in the debug_log file. The attached image demonstrates successful testing. Feel free to merge the PR and run the tests again; the pytest error is unrelated to this update.

I intend to propose further enhancements once I return from my travels. Apologies for any inconvenience caused.
![image](https://github.com/gpt-engineer-org/gpt-engineer/assets/71301573/8afedd85-31d0-4d9a-b148-cf2e2db85138)
