### ISSUE TITLE
Missing support for the vision capabilities in the new model gpt-4-turbo 

### ISSUE THREAD

**Issue by fre-bod** [gpt-engineer-org/gpt-engineer#1112]
## Expected Behavior

When using the model gpt-4-turbo, I expect the vision capabilities to work so that I can send in image inputs using the --image_directory flag.

## Current Behavior

When using the --image_directory flag and the model gpt-4-turbo, the images in the directory are ignored and not sent to the model.

##
A simple fix would be to update the dependency to langchain to reference v0.1.16 or later that have better support for gpt-4-turbo.
https://github.com/langchain-ai/langchain/releases/tag/v0.1.16

And: 

In core/ai.py one could change this on row 110:
`self.vision = "vision" in model_name`
to
`self.vision = "vision" in model_name or model_name in ["gpt-4-turbo", "gpt-4-turbo-2024-04-09"]`

**Comment by viborc** [comment]
@ATheorell, do you think you could take a look into this? Or, I can ask Theo since he also contributed to the vision capabilities earlier.

**Comment by ATheorell** [comment]
@TheoMcCabe can you look at this?

**Comment by TheoMcCabe** [comment]
thanks for providing the fix @fre-bod ! ill commit this
