### ISSUE TITLE
TypeError: Object of type Prompt is not JSON serializable – uploading learning

### ISSUE THREAD

**Issue by AntonOsika** [gpt-engineer-org/gpt-engineer#1115]
When trying to upload learning if it worked or not it can't serialize the "Prompt" class

@TheoMcCabe do you think we could have a fix?

(for now I think it's OK to serialize by just saying `has_image: true`)
<img width="713" alt="image" src="https://github.com/gpt-engineer-org/gpt-engineer/assets/4467025/cc61f895-4eb2-4e38-a600-d9b3a02cf710">

**Comment by TheoMcCabe** [comment]
yep ill take a look

**Comment by AntonOsika** [comment]
Great thanks Theo

Anton Osika
