### ISSUE TITLE
Error while improving the project: 'ascii' codec can't encode character '\u2019' in position 7: ordinal not in range(128)

### ISSUE THREAD

**Issue by adspiceprospice** [gpt-engineer-org/gpt-engineer#1119]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/

## Expected Behavior

Was giving gptengineer a javascript project i've been working on to extend it

## Current Behavior

Error while improving the project: 'ascii' codec can't encode character '\u2019' in position 7: ordinal not in range(128)
Could you please upload the debug_log_file.txt in /Users/adrian/Documents/GitHub/gpt-engineer/projects/simulator/.gpteng/memory folder to github?
Error while improving the project: 'ascii' codec can't encode character '\u2019' in position 7: ordinal not in range(128)
Could you please upload the debug_log_file.txt in /Users/adrian/Documents/GitHub/gpt-engineer/projects/simulator/.gpteng/memory folder to github?

No changes applied. Could you please upload the debug_log_file.txt in /Users/adrian/Documents/GitHub/gpt-engineer/projects/simulator/.gpteng/memory folder in a github issue?

## Failure Information

Information about the failure, including environment details, such as LLM used.

### Failure Logs

If your project includes a debug_log_file.txt, kindly upload it from your_project/.gpteng/memory/ directory. This file encompasses all the necessary logs. Should the file prove extensive, consider utilizing GitHub's "add files" functionality.

2000 lines of javascript from my project +
CONSOLE OUTPUT:
Error while improving the project: 'ascii' codec can't encode character '\u2019' in position 7: ordinal not in range(128)
Could you please upload the debug_log_file.txt in /Users/adrian/Documents/GitHub/gpt-engineer/projects/simulator/.gpteng/memory folder to github?

**Comment by TheoMcCabe** [comment]
I can have a little look at this but im not sure where the issue is as all files should be loaded as utf-8 not ascii 

Quick fix is to find the unicode characre in your file which is a right quotation mark ’ and replace it with a normal quotation mark ' with a find and replace

**Comment by TheoMcCabe** [comment]
Ive experimented with adding a right quotation mark to the prompt and to a code file and ive not been able to reproduce the issue. Can you have a look to see if you can find where this right quotation is? and also would be good to know what version of gpte you are running?  

Thanks

**Comment by adspiceprospice** [comment]
Thanks for looking into it Theo, after seeing your reaction, i tried it again today, it now it just worked, did not complain about those characters any more. So i guess this is no longer an issue.
Thanks again,
Cheers,
Adrian
