### ISSUE TITLE
Urgent - all PRs blocked because of failing tests

### ISSUE THREAD

**Issue by TheoMcCabe** [gpt-engineer-org/gpt-engineer#1122]
Tests run fine locally but fail on the build server. This is blocking my 2 prs and seeminly every other PR on the repo. 

@ATheorell  i feel like its to do with caching and API keys - would you be able to give us a quick fix? 

Also @similato87 were you looking at removing the catching? do you know anything about why these are failing?

**Comment by ATheorell** [comment]
@TheoMcCabe caching is removed.

There is one test that uses an openai key and did so successfully on github for a while, though 
stopped working recently. My suggestion is that we remove this test for now, until we have a working key. However, this means that we have to test manually that gpte runs locally before merging.

**Comment by ATheorell** [comment]
handled with hotfix in #1123

**Comment by TheoMcCabe** [comment]
Thanks for sorting @ATheorell . hero

**Comment by ATheorell** [comment]
No problem! I see this as a temporary fix though. We can keep the issue open for now
