### ISSUE TITLE
The Video demo on the Main Repo is Corrupted

### ISSUE THREAD

**Issue by fire17** [gpt-engineer-org/gpt-engineer#1130]
Just wanted to let you know ❤️ 
All the best

**Comment by viborc** [comment]
Hey @fire17 - what OS and browser are you using since I cannot reproduce this issue?

**Comment by fire17** [comment]
I'm on regular chrome...
Only the first 2 seconds loaded when I tried

I'll try to update and see if it was on my end... 
Thanks for responding :)

**Comment by viborc** [comment]
Sure, be sure to let us know so we can investigate.

**Comment by viborc** [comment]
Hey, @fire17, did you get the chance to check it? If not, since we are not seeing the same issue, I'll be closing this issue tomorrow (Friday).
