### ISSUE TITLE
how to set gpt-4o

### ISSUE THREAD

**Issue by bluegithupu** [gpt-engineer-org/gpt-engineer#1150]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/

## Description
A clear and concise description of how the documentation at https://gpt-engineer.readthedocs.io/en/latest/ is providing wrong/insufficient information.

## Suggestion
How can it be improved

**Comment by viborc** [comment]
Hey, we'll take a look into this; in the meantime, @AntonOsika worked on a PR where GPT-4o will be a default model. You can check it here https://github.com/gpt-engineer-org/gpt-engineer/pull/1151

**Comment by TheoMcCabe** [comment]
Anton has merged his code now, and gpt-4o is the default model - so you should just be able to pull the latest code and run as per normal @bluegithupu

**Comment by viborc** [comment]
Hey @bluegithupu - we just mentioned this during our technical planning meeting. You should be able to specify different models using our model argument.

Generally, you can use 
```
gpte --help
``` 
Then it will show you that there's a model argument taking model id string which you can use for different models (like the gpt-4-turbo you mentioned or the previous default gpt-4-turbo.

![image](https://github.com/gpt-engineer-org/gpt-engineer/assets/48092564/5deadbb8-93c9-43dc-876b-c0c5b62bb110)

This screenshot is courtesy of @zigabrencic 🙏

**Comment by joshwand** [comment]
the help flag should be added to the documentation, and each option should be fully document as well
