### ISSUE TITLE
Can't run poetry install. Greenlet not supporting PEP 517 builds.

### ISSUE THREAD

**Issue by iliyan-pigeon** [gpt-engineer-org/gpt-engineer#1152]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

What is the current behavior?

## Failure Information

Information about the failure, including environment details, such as LLM used.

### Failure Logs

If your project includes a debug_log_file.txt, kindly upload it from your_project/.gpteng/memory/ directory. This file encompasses all the necessary logs. Should the file prove extensive, consider utilizing GitHub's "add files" functionality.

**Comment by viborc** [comment]
This is likely related to your local installation. We are closing it for now, but if you encounter more issues, let us know.
