### ISSUE TITLE
Azure Deployment Name Bug

### ISSUE THREAD

**Issue by JiaCYu** [gpt-engineer-org/gpt-engineer#1153]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/

## Expected Behavior

There shouldn't be an error with the model name.

### Deployment name seems to mix with model name.

Everything seems to work perfectly and code is being made:
![image](https://github.com/gpt-engineer-org/gpt-engineer/assets/145611451/9fd4fcf5-d78e-4179-9406-a98867a9dfc1)

But then an error pops up telling me that the model doesn't exist and it takes my Azure OpenAI deployment name and says it's not a model.
![image](https://github.com/gpt-engineer-org/gpt-engineer/assets/145611451/de5d275e-aa79-4d55-899e-ecf87d7a4261)

Here is the command style I used following these instructions from here: https://gpt-engineer.readthedocs.io/en/latest/open_models.html
![image](https://github.com/gpt-engineer-org/gpt-engineer/assets/145611451/987113ca-0616-4a38-9f35-ccec2cebda5d)

`gpt-engineer --azure [redacted_endpoint_url] ./snake_game/ [redacted_deployment_name]`

## Additional Failure Information

Using Azure OpenAI with gpt-4-turbo deployed with a different deployment name. Only installed gpt-engineer in a virtual environment.

**Comment by JiaCYu** [comment]
I just reread the instructions and I realized that the Azure Deployment Name should be the model name as well. Which kind of sucks because there are a bunch of projects dependent on that deployment name and a lot refactoring would have to be done.

**Comment by captivus** [comment]
If I understand the issue you're reporting correctly, this is due to the parameters that OpenAI expects for Azure deployments of its model and is not a GPTE-specific issue.

**Comment by captivus** [comment]
@viborc I have a meeting conflict with today's dev meeting, but I can speak more about this if the issue isn't resolved during the meeting today.

**Comment by viborc** [comment]
Sounds good @captivus! I might assign you to this one if we don't figure it out during the meeting!

**Comment by viborc** [comment]
We decided to use your very generous offer to help us with this @captivus and @zigabrencic mentioned that he'll add some comments here, too!

**Comment by zigabrencic** [comment]
Hey.

As discussed in the meeting today. My proposal would be to to sync the Azur part with same approach we use open models and Open router. For example (from [here](https://github.com/gpt-engineer-org/gpt-engineer/blob/main/docs/open_models.md)):

```
export OPENAI_API_BASE="https://openrouter.ai/api/v1"
export OPENAI_API_KEY="sk-key-from-open-router"
export MODEL_NAME="meta-llama/llama-3-8b-instruct:extended"
```

```
gpte <project_dir> $MODEL_NAME --lite --temperature 0.1
```

Instead of using custom `--azure` flag. 

@captivus what do you think? I don't know their hosting specs so I'm not sure if it's doable.

**Comment by captivus** [comment]
Looking at this further, I think the bug may be ours and due to the way that we implement the model version in an opinionated way:

https://github.com/gpt-engineer-org/gpt-engineer/blob/66986568a116308743bc624f8ffbabe8b82ce897/gpt_engineer/core/ai.py#L349

Let's discuss in our dev meeting.

**Comment by captivus** [comment]
More thoughts here.  @JiaCYu can you please set the `OPENAI_API_VERSION` environment variable with your deployment name and try again?  The internals I've linked to above show how we handle a missing environment variable, and is consistent with the error messages you've provided.  

Please try and feedback!

**Comment by JiaCYu** [comment]
@captivus Sorry for the late reply.

I set `OPEN_API_VERSION` in the environmental variable in powershell, and I still get the same error as I do from the original post:
![image](https://github.com/gpt-engineer-org/gpt-engineer/assets/145611451/cf9f8223-4a57-4b67-aace-bcc9513cfec0)


The deployment I have is named `gpt-4-[redacted, but there are 4 letters here]` and the deployment of the actual model is just gpt-4-turbo ver. 0125-preview:
![image](https://github.com/gpt-engineer-org/gpt-engineer/assets/145611451/b512762a-f429-4a9a-95eb-a522e9c91a85)

**Comment by JiaCYu** [comment]
So, the "Unknown model" that the error message contains is my deployment name that I mentioned here:

> The deployment I have is named `gpt-4-[redacted, but there are 4 letters here]`

The thing is, my deployment name is different than the actual model name itself.

> Also, kindly share text outputs in addition to screenshots if additional debugging is needed.

Here is the command I use with gpt-engineer:

![image](https://github.com/gpt-engineer-org/gpt-engineer/assets/145611451/efd1bc38-8f70-408e-b284-c7622961c5b9)
_The first red box is my azure endpoint and the last red box is the last 4 letters of my deployment name on azure._

I think it may be taking my deployment name and entering it as the model name at some point. I don't think there is a way to enter the model name separately.

**Comment by rohansasmal123** [comment]
Passing azure deployment name in --model tag solved the issue.
Here is the command:
`gpt-engineer --azure <AZURE_OPENAI_API> --model <DEPLOYMENT_NAME> ./projects/guideline-store`.

**Comment by JiaCYu** [comment]
> Passing azure model deployment name in --model tag solved the issue. Here is the command: `gpt-engineer --azure <AZURE_OPENAI_API> --model <DEPLOYMENT_NAME> ./projects/snake`

![image](https://github.com/gpt-engineer-org/gpt-engineer/assets/145611451/638105f0-759d-4411-a79d-af0b9e4b2a4f)

**Comment by captivus** [comment]
> Passing azure model deployment name in --model tag solved the issue.
> 
> Here is the command:
> 
> `gpt-engineer --azure <AZURE_OPENAI_API> --model <DEPLOYMENT_NAME> ./projects/snake`
> 
> 
> 
> 

This is the expected behavior @JiaCYu. I see your response indicating that this hasn't worked for you. Assuming you're escaping characters in the name of your model, as needed from the shell, I'm at a loss as to how to further debug the issue.

**Comment by captivus** [comment]
> Can you please try referencing one of the available deployments in your environment, as shown in the output you provided? The error suggests that you are trying to use a model that is unavailable.
> 
> ![image](https://private-user-images.githubusercontent.com/366332/337724944-7844eb34-1363-4d4a-a761-e0a4507ef0e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NjY1NjYsIm5iZiI6MTcxODY2NjI2NiwicGF0aCI6Ii8zNjYzMzIvMzM3NzI0OTQ0LTc4NDRlYjM0LTEzNjMtNGQ0YS1hNzYxLWUwYTQ1MDdlZjBlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QyMzE3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmU0ZjcyZDliODE0ZTI1YTExZDc1YjAxNDY4NzcxYjhmOGM5OTQwNTIyNTNhYmYyNTcwMmQxMzhjMjhkNDJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AqoyXGPks-gVSfnV4hH5xir4ijmq_jUVKG3UqrPE7-Y)
> 
> Also, kindly share text outputs in addition to screenshots if additional debugging is needed.
> 
> We will upgrade the default version to use the latest supported model in Azure, which is `2024-05-01-preview` per [the docs](https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation).

I've just merged the upgrade to the default version that I suggested we'd incorporate.  Does that change anything for you?

**Comment by JiaCYu** [comment]
It seems I am blocked due to the situation I'm in and am no longer allowed to test it :(
Thank you @captivus for keeping up with this and helping me out.

**Comment by viborc** [comment]
Hey @JiaCYu what do you mean you are blocked due to the situation?

**Comment by JiaCYu** [comment]
> Hey @JiaCYu what do you mean you are blocked due to the situation?

It's a personal reason due to to the situation I'm in, not anything of gpt-engineer's team's fault. I'm not allowed to use pypi or npm anymore :'(

**Comment by viborc** [comment]
Got it! Good luck with everything, then @JiaCYu. I hope we'll see you contributing to gpt-engineer again in the future!
