### ISSUE TITLE
Could not build wheels for pyarrow, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by Thinking80s** [gpt-engineer-org/gpt-engineer#1160]
ERROR: Could not build wheels for pyarrow, which is required to install pyproject.toml-based projects

<img width="1072" alt="image" src="https://github.com/gpt-engineer-org/gpt-engineer/assets/338079/86b8bcb7-eba2-4c75-85a3-5d53cb3344d0">

**Comment by viborc** [comment]
Hey, @Thinking80s, can you share a bit more info about the OS/environment in which this happened?

**Comment by Thinking80s** [comment]
<img width="298" alt="image" src="https://github.com/gpt-engineer-org/gpt-engineer/assets/338079/fea2721a-484c-41ae-bb5a-4a81ebd8fc16">

**Comment by viborc** [comment]
Okay, we'll take a look into this! Thank for sharing!

**Comment by viborc** [comment]
Hey, @Thinking80s - we just had our meeting, and I wanted to double-check something with you. Did you encounter an issue you mentioned while running the Docker image or some other way? If it was a Docker image, then possibly a #1161 Hotfix should be able to resolve it. (Thanks, @k1lgor, for this; I added @zigabrencic to also review it and check it).

If this is not an issue in Docker, then it might be an issue with your local Python installation/setup.

Let us know!

**Comment by viborc** [comment]
Hey, @Thinking80s! We just made a [new release - v0.3.1](https://github.com/gpt-engineer-org/gpt-engineer/releases/tag/v0.3.1), and the Docker hotfix is included. Can you check and see if this solves the issue you mentioned and let us know?

**Comment by viborc** [comment]
I'm closing this now, but if there are any questions, feel free to (re)open it, @Thinking80s.
