### ISSUE TITLE
Add support for Claude models

### ISSUE THREAD

**Issue by slowpoke111** [gpt-engineer-org/gpt-engineer#1280]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/
 - Consider adding the label "good first issue" for interesting, but easy features.

## Feature description
Add support for using Anthropic's Claude models. They can be accessed through the anthropic python library and have similar syntax to the openai module.

## Motivation/Application
This could allow for more user control over the results as Claude performs better on some tasks.

**Comment by chaelli** [comment]
imho that already works
try 
`export ANTHROPIC_API_KEY=......`
and then
gpte --model "claude-3-5-sonnet-20241022"

**Comment by Erchoc** [comment]
But we can't custom the ANTHROPIC_API_HOST ?
