### ISSUE TITLE
Injecting malicious code

### ISSUE THREAD

**Issue by Lindfeldto** [gpt-engineer-org/gpt-engineer#270]
Add a test to check that the AI is not injecting malicious code outside the workspace @AntonOsika 
[../../src/main.py] 👎 

```python
def test_files_are_local():
    chat = textwrap.dedent(
        """
    All this will soon be over.

    [../../src/main.py]  
    ```python
    print("Goodbye, World!")
    ```
    """
    )
```

**Comment by AntonOsika** [comment]
Would be great with a PR on this!

**Comment by CenekSanzak** [comment]
Can I do this

**Comment by patillacode** [comment]
Feel free to pick this one up @CenekSanzak !

Thanks!

**Comment by Lindfeldto** [comment]
ChatGPT suggest the following checks (after some massage)  @CenekSanzak 

```python
import os
import pytest

def is_valid_relative_path(path):
    invalid_prefixes = ["..", "/", "~", "-", " "]

    return (
        not any(path.startswith(prefix) for prefix in invalid_prefixes)
        and not os.path.isabs(path)
    )


@pytest.mark.parametrize("path, expected_result", [
    ("path/to/file.txt", True),        # Valid relative path
    ("../file.txt", False),             # Invalid: starts with ".."
    ("/root/file.txt", False),          # Invalid: starts with "/"
    ("~/file.txt", False),              # Invalid: starts with "~"
    ("./file.txt", True),               # Valid relative path
    ("-file.txt", False),               # Invalid: starts with "-"
    (" file.txt", False),               # Invalid: starts with space
])
def test_is_valid_relative_path(path, expected_result):
    assert is_valid_relative_path(path) == expected_result


# Additional test case
def test_is_valid_relative_path_empty_string():
    assert is_valid_relative_path("") == False
```

**Comment by sciencehas** [comment]
that is slightly concerning, did AI actually write that? Are we going somewhere? - is it? or the planet?

**Comment by LopeKinz** [comment]
> that is slightly concerning, did AI actually write that? Are we going somewhere? - is it? or the planet?

chat gpt can write something like this but its unlikely to happen

**Comment by jondot** [comment]
> ChatGPT suggest the following checks (after some massage) @CenekSanzak
> 
> ```python
> import os
> import pytest
> 
> def is_valid_relative_path(path):
>     invalid_prefixes = ["..", "/", "~", "-", " "]
> 
>     return (
>         not any(path.startswith(prefix) for prefix in invalid_prefixes)
>         and not os.path.isabs(path)
>     )
> 
> 
> @pytest.mark.parametrize("path, expected_result", [
>     ("path/to/file.txt", True),        # Valid relative path
>     ("../file.txt", False),             # Invalid: starts with ".."
>     ("/root/file.txt", False),          # Invalid: starts with "/"
>     ("~/file.txt", False),              # Invalid: starts with "~"
>     ("./file.txt", True),               # Valid relative path
>     ("-file.txt", False),               # Invalid: starts with "-"
>     (" file.txt", False),               # Invalid: starts with space
> ])
> def test_is_valid_relative_path(path, expected_result):
>     assert is_valid_relative_path(path) == expected_result
> 
> 
> # Additional test case
> def test_is_valid_relative_path_empty_string():
>     assert is_valid_relative_path("") == False
> ```

better to fully resolve using the stdlib, and then assert that the resolved path is a descendant of the current path.

**Comment by SumitKumarDev10** [comment]
Hey! I got an **idea**.
Why don't we initialise **Git** outside the directory of the code which runs the **gpt-engineer** with the command `git init`?
After the code is run, we can do `git status` and then see the changes made.
If anything outside the directory(in which the gpt-engineer is run) is changed, we can declare that something is wrong with the code and it may be **malicious**.

**Comment by AntonOsika** [comment]
Still happy to get a PR on this

**Comment by umair313** [comment]
is the git been added into the project?

**Comment by viborc** [comment]
@CenekSanzak, are you still interested in taking up on this issue?
