### ISSUE TITLE
Explicit "code review" step + self healing code

### ISSUE THREAD

**Issue by AntonOsika** [gpt-engineer-org/gpt-engineer#682]
The proposal is most easily explained with specific steps to carry out:

After the generation finishes, we would:
1. Ask the LLM what a QA person would manually test based on the project specification ("does snake move", "does the snake change direction when key is pressed" etc)
2. For each QA tsak, ask the LLM if the generated code is expected to pass the QA task just by inspecting the code, or if something seems to be broken
3. Advanced: Let the LLM optionally output _code blocks_ that overwrites files if it detects that something is broken in the QA, and it can fix it

**Comment by ATheorell** [comment]
I think point 3 should be left untouched in this issue for now, since such functionality is underway in #650 and #727 .

**Comment by yskolnick** [comment]
I am going to work on this on Monday or Tuesday.

**Comment by TheoMcCabe** [comment]
@yskolnick Hows this going are you still working on it? This would be useful for the hackathon

**Comment by yskolnick** [comment]
Hey! Apologies.  I got distracted with other work.  I will work on it in next few days.

**Comment by AntonOsika** [comment]
Great @yskolnick. Looking forward to see how this works over the weekend!
