### ISSUE TITLE
Improve code mode hits token limit for medium sized programs

### ISSUE THREAD

**Issue by cloudbow** [gpt-engineer-org/gpt-engineer#716]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/

## Expected Behavior
The prompt should be taken care and its side effects should be created as a diff in the existing code. 
Please describe the behavior you are expecting.

## Current Behavior
When I try to use the -i /improve existing code the tool just throws out an error that I am rate limited.

INFO:openai:error_code=rate_limit_exceeded error_message='Rate limit reached for 10KTPM-200RPM in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.' error_param=None error_type=tokens message='OpenAI API error received' stream_error=False
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for 10KTPM-200RPM in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues..
INFO:openai:error_code=rate_limit_exceeded error_message='Rate limit reached for 10KTPM-200RPM in organization org-xxxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.' error_param=None error_type=tokens message='OpenAI API error received' stream_error=False
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for 10KTPM-200RPM in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues..
INFO:openai:error_code=rate_limit_exceeded error_message='Rate limit reached for 10KTPM-200RPM in organization org-xx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.' error_param=None error_type=tokens message='OpenAI API error received' stream_error=False
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for 10KTPM-200RPM in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues..
INFO:openai:error_code=rate_limit_exceeded error_message='Rate limit reached for 10KTPM-200RPM in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.' error_param=None error_type=tokens message='OpenAI API error received' stream_error=False
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised RateLimitError: Rate limit reached for 10KTPM-200RPM in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues..
INFO:openai:error_code=rate_limit_exceeded error_message='Rate limit reached for 10KTPM-200RPM in organization org-xxx on tokens per min. Limit: 10000 / min. Please try again in 6ms. Cont
What is the current behavior?

## Failure Information

Information about the failure, including environment details, such as LLM used.

### Steps to Reproduce

If possible, provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Any relevant log snippets or files here.

**Comment by cloudbow** [comment]
why is this working in the new project mode if its a rate limitting problem? Isn't it because we are not working within the rate limit for the -i feature?

**Comment by pbharrin** [comment]
How much code are you sending over?   

New code mode just sends your prompt and some system prompts, so it doesn't send many tokens.  Existing code mode will send over all the code you add to the context.  That is why you are getting this error.  Try existing code mode with a few files.  

There is a way we. Plus send over a "map" of all your code, but it isn't the height priority right now.  If you are a decent coder and want to contribute, I can give you more information.

**Comment by cloudbow** [comment]
I am sending a large file with 1800 lines of code. yes I will try contributing if you can point me to the right place.

**Comment by pbharrin** [comment]
Great, here is the basic idea: Use [Universial Ctags](https://github.com/universal-ctags/ctags) to send over a "map" of the current project, rather than just send over all the files.  
See [this link from a similar project](https://aider.chat/docs/ctags.html) for more info on Ctags.  

So when someone launches the `gpt-engineer -i` command we should:
Check if the command `ctags` exists if it does we should create a ctag map from the current project.  If the map already exists, we can skip this.  

During the improve prompt we will have to modify the prompt to say something like: "the project is described in the following ctag map" instead of talking about the actual files.  

That should be it!  Here are the big steps:

1. install ctags and figure out how to generate ctag files for a project.  
2. modify the improve code prompt if the ctag file exists.

**Comment by heijligers** [comment]
Awesome recommendation. Looking into Ctags and Aider now.

**Comment by ATheorell** [comment]
I added this to a new milestone about removing technical bottlenecks (for example imposed by the context token limitation). PRs on this are thus strongly encouraged @heijligers :)

**Comment by zdanl** [comment]
It truly is a random thought, but has anybody experimented with giving GPT4 encoded (base) code and ask it to interpret it inline? Secondly, what came to mind, is giving it very concise Python bytecode.

**Comment by ATheorell** [comment]
I'm afraid I don't see the connection at all. This issue is about the (hard) token limits of single prompts. I don't see how load balancing can change that. Decomposing a single prompt into multiple prompts is a hard problem.

Thanks for your great work with liteLLM @krrishdholakia
