### ISSUE TITLE
Improve UX for selecting files when using -i flag

### ISSUE THREAD

**Issue by AntonOsika** [gpt-engineer-org/gpt-engineer#725]
Improve the user experience for selecting files

- Generate a tree (instead of list) representation of the code (workspace) in a text file. Similar to output of `tree` command
- Allow users to edit this file directly.
- Users can comment out files they do not want to feed into the LLM prompt.
- Include instructions within comments of the generated text file to explain how to use the file.
- Implement as the primary method for selecting files.
- Let the CLI give the user the option to open the file list in the default editor (rather than using tkinter tool)
- **Benefit**: Users can use their editors and toggle file selections using IDE keyboard shortcuts, tailoring their experience with the GPT engineer.

More nice to haves:
- Let it be a .toml file, which supports comments
- Allow syntax for excluding patterns. Such as `node_modules` `__pycache__` `*.pyc` in the .toml file
- Support having multiple "configs" in the .toml file, that can be selected with CLI argument. Useful for asking for edits in separate parts of codebase

**Comment by SabareeshGC** [comment]
what about .ignore file that we can configure

**Comment by ATheorell** [comment]
This task supersedes #667 -> implementing #725 solves #667

**Comment by similato87** [comment]
Hi @ATheorell ,

I've implemented the tree-style file selection feature in the recent PR(https://github.com/gpt-engineer-org/gpt-engineer/pull/937) and would greatly appreciate your review. This update simplifies the file selection process for users, allowing them to choose files via a .toml configuration directly from the terminal and view their selections in a tree-style format. There is a GIF showing the process in the PR.

Please take a look at the changes and provide your feedback. Also, it would be helpful to know if there are any additional requirements for tests or if you'd like to see more features or enhancements related to this update.

**Comment by TheoMcCabe** [comment]
Closing as similato has done great work on this

**Comment by PierrunoYT** [comment]
I don't like it

**Comment by captivus** [comment]
> I don't like it

This is unhelpful. We'd welcome PRs reflecting thoughtful input.

**Comment by PierrunoYT** [comment]
> > I don't like it
> 
> This is unhelpful. We'd welcome PRs reflecting thoughtful input.

I posted some ideas

**Comment by captivus** [comment]
That doesn't give you license to subsequently post unhelpful remarks. Please be helpful and productive.

Closing this thread. Thanks again for your work @similato87!
