### ISSUE TITLE
Ability to access local CodeLlama

### ISSUE THREAD

**Issue by since66** [gpt-engineer-org/gpt-engineer#900]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/
 - Consider adding the label "good first issue" for interesting, but easy features.

## Feature description
Your project is great, one question I ask is whether it is possible to access the local CodeLlama and code through CodeLlama!

## Motivation/Application
Because chatapp has token limitation, usually big projects have a lot of characters, if you can realize local CodeLlama docking that would be better, thanks!

**Comment by ergunkocak** [comment]
CodeLlama has also a 4K response limit right?

**Comment by ergunkocak** [comment]
Sample in ".env" file:

OPENAI_API_KEY=sk-111111111111111111111111111111111111111111111111
OPENAI_API_BASE=http://localhost:5001/v1

**Comment by haseeb-heaven** [comment]
Good feature request but you forgot to mention which codellama model? there are multiple code-llama models instruct and chat models available.
And you didnt mentioned system requirements of these models to install them.
And codellama models in windows are very instable to download only works fine Good in Linux/MacOS via [OoLama](https://github.com/jmorganca/ollama)

**Comment by haseeb-heaven** [comment]
> CodeLlama has also a 4K response limit right?

4K is not that much now GPT 4 has 32k and Claude 2 has 100K token response limit.

**Comment by ATheorell** [comment]
Closing as solved
