### ISSUE TITLE
Automatic benchmarking of gpt-engineer with MBPP

### ISSUE THREAD

**Issue by AntonOsika** [gpt-engineer-org/gpt-engineer#914]
## Feature description
We have a way to easily add benchmarks:

https://www.loom.com/share/206805143fbb4302b5455a5329eaab17?sid=f689608f-8e49-44f7-b55f-4c81e9dc93e6

This issue is about looking into if [mbpp](https://huggingface.co/datasets/mbpp) is a good benchmark to add and then add a simple version of it.

**Comment by azrv** [comment]
@AntonOsika assign to me
