### ISSUE TITLE
Make GPT able to create a draft document in word format from the following sources in Slack chat, emails....

### ISSUE THREAD

**Issue by montao** [gpt-engineer-org/gpt-engineer#919]
As a technical writer, I would like GPT to draft incident reports (incident retro document and incident post-mortem documents for example) with input from unstructured sources. I heard it can be done if it is not already available. Concrete example would be to generate a draft document in word format (e.g. in google docs) from a template and GPT would take input from very unstructured chats, emails and maybe system documentation to complete a task that would otherwise take hours of manual technical writing for a human that might not be better at anything.

## Feature description

Make GPT create a draft document with input from unstructured sources e.g. Slack chat, document templates, and emails. 
If I understood correctly, this idea already exists somewhere, but it's not immediately available and would be valuable and save many hours for many organizations. 

## Motivation/Application
Why is this feature useful? Writing a document after a major incident happened at a company, for example, if main infrastructure breaks down temporarily and everything stops working (e.g. Facebook APIs stopped working in September 2021), takes 10s or 100s of work hours of manual work requiring technical knowledge but it can be automated and it is automated already with GPT from what I heard at some workplaces.

I hope you like the idea, or if you need clarification I will be happy to explain more.

**Comment by ATheorell** [comment]
Good idea, but sounds a bit far fetched for gpt-engineer. Maybe AutoGPT would be a better fit?
