### ISSUE TITLE
No module named '_tkinter' 

### ISSUE THREAD

**Issue by yairVanti** [gpt-engineer-org/gpt-engineer#951]
i pulled the latest version from git
edited the .env file
put my prompt in the projects/{my_project}
ran poetry install , and shell.
then i ran gpte projects/{my_project}
and got this error :
`  File "/Users/me/Library/Caches/pypoetry/virtualenvs/gpt-engineer-dSlWqTyf-py3.11/bin/gpte", line 3, in <module>
    from gpt_engineer.applications.cli.main import app
  File "/Users/me/openAI/gpt-engineer/gpt_engineer/applications/cli/main.py", line 40, in <module>
    from gpt_engineer.applications.cli.file_selector import ask_for_files
  File "/Users/me/openAI/gpt-engineer/gpt_engineer/applications/cli/file_selector.py", line 44, in <module>
    import tkinter as tk
  File "/usr/local/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
`
this is my python :
`(gpt-engineer-py3.11) ➜  gpt-engineer git:(main) ✗ which python
/Users/me/Library/Caches/pypoetry/virtualenvs/gpt-engineer-dSlWqTyf-py3.11/bin/python`

**Comment by ATheorell** [comment]
This question comes up routinely. Tkinter is not a regular dependency, since it comes by default with most python distributions, not always though, as in your case. See this: https://www.pythonguis.com/installation/install-tkinter-linux/
