### ISSUE TITLE
Cost forecast for usage of GPT 4 endpoints

### ISSUE THREAD

**Issue by RukshanJS** [gpt-engineer-org/gpt-engineer#964]
## Description
Currently, the usage of the tool would only give the **actual cost** of the operation of using the Open AI API **after the fact.** This is helpful, but what if the cost is far beyond the budget of the user?

## Suggestion
I think it's better we give a rough estimate of the cost that's going to be incurred based on the tokens (or some other way). Thereby, we can ask the user whether he wants to bear that amount and continue with the operation.

Something like below,

`This operation will cost you $0.05 for using the Open AI API. Do you want to accept and continue with the operationr? (y/N)`

**Comment by ErikBjare** [comment]
It's hard to give a meaningful estimate in advance of how many output tokens will be used, although the number of input tokens would be known.

Asking if they want to continue would also need another ask for confirmation step, which I personally would always want to skip, thus would need some flag or config to disable, adding further complexity.

I question if most people really need/want this?

If users are on a limited budget, they could just set their spend limit in the OpenAI API settings.

**Comment by RukshanJS** [comment]
> It's hard to give a meaningful estimate in advance of how many output tokens will be used, although the number of input tokens would be known.
> 
> Asking if they want to continue would also need another ask for confirmation step, which I personally would always want to skip, thus would need some flag or config to disable, adding further complexity.
> 
> I question if most people really need/want this?
> 
> If users are on a limited budget, they could just set their spend limit in the OpenAI API settings.

I'm completely with you on not having unnecessary prompts for the user. Here's why i thought of this. 

Yesterday, I was creating an informational video on this tool and during the process i executed it to generate some simple codebase. And it did perfectly, but to find `API cost : $0.05` or something at the end of the execution was a 'little surprise' to me. (I have used the tool earlier but completely forgot it uses GPT 4 API key behind the scenes.

So I thought it would be a 'nice-to-have'. Otherwise, what if i instruct it to generate a fairly complex codebase and it gives me a bill of say $5 unexpectedly? still not a lot but I hope I conveyed my point.

I'm very much open to discussion on this.

**Comment by ATheorell** [comment]
Hi,
@RukshanJS thanks for the idea. From other comments it seems like budget is top of mind for many users, so I think your thoughts are relevant. For some combinations of flags, where the number of executions are known, it would be possible to provide an upper bound for the cost. 

I see two problems:
1) I agree with @ErikBjare that it will complicate the workflow. One possible way would be to print the number directly and then tell the user to abort the run dynamically if the price tag is too much. This would bypass the additional confirmation step.
2) We are currently low on people developing features and the core team is focused on the most pressing functionality. If you are willing to implement this yourself, we should consider it.

**Comment by RukshanJS** [comment]
> Hi, @RukshanJS thanks for the idea. From other comments it seems like budget is top of mind for many users, so I think your thoughts are relevant. For some combinations of flags, where the number of executions are known, it would be possible to provide an upper bound for the cost.
> 
> I see two problems:
> 
> 1. I agree with @ErikBjare that it will complicate the workflow. One possible way would be to print the number directly and then tell the user to abort the run dynamically if the price tag is too much. This would bypass the additional confirmation step.
> 2. We are currently low on people developing features and the core team is focused on the most pressing functionality. If you are willing to implement this yourself, we should consider it.

HI, sorry for the late reply. Yes I would love to work on this. I'm still learning this stuff so would love to take tasks like this. Let me know.
