### ISSUE TITLE
Discord invite link expired

### ISSUE THREAD

**Issue by phitoduck** [gpt-engineer-org/gpt-engineer#966]
## Description
A clear and concise description of how the documentation at https://gpt-engineer.readthedocs.io/en/latest/ is providing wrong/insufficient information.

<img width="600" alt="image" src="https://github.com/gpt-engineer-org/gpt-engineer/assets/32227767/ff30bcb4-d891-4df5-888d-e1f600f14b11">

**Comment by ATheorell** [comment]
Thanks for letting us know. Currently, the docs don't even compile. We are working on it.

**Comment by phitoduck** [comment]
I'm a fool. Somehow the issue was not with the discord link, but the way I was personally logged into discord.
