### ISSUE TITLE
Support for RAG? "Bring your own docs"

### ISSUE THREAD

**Issue by phitoduck** [gpt-engineer-org/gpt-engineer#967]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/
 - Consider adding the label "good first issue" for interesting, but easy features.

## Feature description

Sorry if I'm missing something obvious. I did a full-text search through the docs, code, and discussions and didn't see any mention of RAG.

I imagine having the ability to index a set of docs, maybe for a Python library like `boto3`, `FastAPI`, `Material UI` for React, etc. which could be used to improve the results of the output.

I think AutoGPT includes steps built into its flows to google search content that could help accomplish the task. I personally think it'd be more responsible to download the docs yourself and point an agent at them offline (to save on bandwidth and load on webservers) but that's just me.

## Motivation/Application

To inform the gptengineer agent about specific tools so that it produces even more relevant answers.

**Comment by ATheorell** [comment]
Thank you for the feedback!
First of all, sorry for the current state of the documentation. It got outdated after a recent refactor. We are working on it.
Regarding RAG: We have an initial experimental RAG implementation. However, after the release of GPT-4 turbo, with massively increased context size, the feature got down prioritized. Currently, we let the user pick what files they want to improve manually. This is of course more cumbersome, but also more stable.
