### ISSUE TITLE
Unicode error - german umlaut

### ISSUE THREAD

**Issue by aliasal** [gpt-engineer-org/gpt-engineer#975]
I try to create a tkinter app with python.

I am german and write my instructions in german. That seems to work more or less, but gpte seems to struggle with german umlauts, like ä, ö or ü.
When it writes code with these symbols, the files it creates are encoded in ansi, not utf-8. Therefore the python-interpreter struggles when processessing them:

  File "C:\Users\Arnd\Desktop 3\GPT Engineer\stundenplan\tabs.py", line 33
    self.teacher_table = Treeview(self, columns=("Langname", "K�rzel"))
                                                                     ^
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xfc in position 1: invalid start byte

  File "C:\Users\Arnd\Desktop 3\GPT Engineer\stundenplan\app.py", line 21
    tab_control.add(self.plaene_tab, text='Pl�ne')
                                                 ^
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe4 in position 2: invalid continuation byte

When I set the file encoding to utf-8 and correct the problematic symbols by hand, the errors go away and the application runs.

**Comment by ATheorell** [comment]
I believe the easiest fix to this is to tell the LLM to only respond in ASCII characters, no matter what language it is prompted in. With that, you should still be able to prompt in German, but the software, including strings and variable names should all be ASCII. Does this at least partly solve your problem?

**Comment by aliasal** [comment]
I didn't try it out, but I guess it would. 
But there are quite a lot of languages on this planet and since utf-8 there should be no reason to fall back on ascii. I am writing python-code in german for many years now and never had any problems with this issue. Such a regression to the 80's oder 90's (I am old enough to remember that) seems weird.
In the end it is not a big deal for me, because I am just toying around, but I thought to mention it to add it to your to-do list.
Thanks
Arnd
