### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by PierrunoYT** [gpt-engineer-org/gpt-engineer#977]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

What is the current behavior?

## Failure Information

Information about the failure, including environment details, such as LLM used.<

I use GPT

### Steps to Reproduce

If possible, provide detailed steps for reproducing the issue.

I tried to run the prompt and it started working but I got this error besides it.

### Failure Logs

C:\Users\pierr>gpte C:\Users\pierr\Desktop\Projects\flappy-bird-game
C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chat_models\__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import AzureChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chat_models\__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\_api\deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
Running gpt-engineer in C:\Users\pierr\Desktop\Projects\flappy-bird-game

C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\_api\deprecation.py:117: LangChainDeprecationWarning: The function `__call__` was deprecated in LangChain 0.1.7 and will be removed in 0.2.0. Use invoke instead.
  warn_deprecated(

**Comment by viborc** [comment]
Can you please provide steps leading to this? It's best to use issue template and add those under the Steps to Reproduce section.

**Comment by PierrunoYT** [comment]
> Can you please provide steps leading to this? It's best to use issue template and add those under the Steps to Reproduce section.

Okay I did

**Comment by viborc** [comment]
We'll check this!

**Comment by viborc** [comment]
@PierrunoYT just to be sure, your code was working, but it threw those messages, is that correct?

**Comment by PierrunoYT** [comment]
Yes correct

**Comment by viborc** [comment]
Okay, here's the thing. The messages you are seeing are not errors but **warnings**. Mostly about some future our current deprecations. They are not errors or bugs, so we will be closing this issue now. Thanks for reporting it, though!
