### ISSUE TITLE
a

### ISSUE THREAD

**Issue by MrDaVinC** [gpt-engineer-org/gpt-engineer#993]
## Policy and info
 - Maintainers will close issues that have been stale for 14 days if they contain relevant answers.
 - Adding the label "sweep" will automatically turn the issue into a coded pull request. Works best for mechanical tasks. More info/syntax at: https://docs.sweep.dev/

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

What is the current behavior?

## Failure Information

Information about the failure, including environment details, such as LLM used.

### Steps to Reproduce

If possible, provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Any relevant log snippets or files here.

**Comment by viborc** [comment]
Hi! This seems to be empty. Can you add more information about this issue?
